# Generated by Django 4.2 on 2024-12-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcareapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='yob',
            field=models.DateField(),
        ),
    ]
